from smart_image_similarity.common.paths import CATALOG_DIR, MODELS_DIR


IMG_PATH = CATALOG_DIR
IMG_H = 64
IMG_W = 64

SEED = 42
TRAIN_RATIO = 0.7
VAL_RATIO = 0.15
TEST_RATIO = 0.15
SHUFFLE_BUFFER_SIZE = 100
NOISE_FACTOR = 0.5

LEARNING_RATE = 1e-3
EPOCHS = 30
TRAIN_BATCH_SIZE = 32
VAL_BATCH_SIZE = 32
TEST_BATCH_SIZE = 32

DENOISER_MODEL_NAME = "denoiser.pt"
DENOISER_MODEL_PATH = MODELS_DIR / DENOISER_MODEL_NAME
