from smart_image_similarity.common.paths import CATALOG_DIR, CHROMA_DIR, MODELS_DIR


IMG_PATH = CATALOG_DIR
IMG_H = 64
IMG_W = 64

SEED = 42
TRAIN_RATIO = 0.7
VAL_RATIO = 0.15
TEST_RATIO = 0.15

LEARNING_RATE = 1e-3
EPOCHS = 30
TRAIN_BATCH_SIZE = 32
VAL_BATCH_SIZE = 32
TEST_BATCH_SIZE = 32

CHROMA_INSERT_BATCH_SIZE = 5000

ENCODER_MODEL_NAME = "deep_encoder.pt"
DECODER_MODEL_NAME = "deep_decoder.pt"
ENCODER_MODEL_PATH = MODELS_DIR / ENCODER_MODEL_NAME
DECODER_MODEL_PATH = MODELS_DIR / DECODER_MODEL_NAME
CHROMA_BACKEND_PATH = CHROMA_DIR
